In [71]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import warnings
import statsmodels.api as sm
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss, roc_auc_score, recall_score, precision_score, average_precision_score, f1_score, classification_report, accuracy_score, plot_roc_curve, plot_precision_recall_curve, plot_confusion_matrix
from sklearn.linear_model import LinearRegression
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [29]:
df= pd.read_csv(r'C:\Users\SHREYAN\Documents\risk.csv')
df

,age,Dead,Sex,Race,Esrd,ALZ,CHF,KIDN,CNC,COPD,...,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR,TotalClaims,RiskT,TotalPre
0,85,0,1,1,0,2,2,2,2,2,...,0,50,10,0,0,0,0,50,1,10
1,65,0,1,1,0,2,2,2,2,2,...,0,0,0,0,700,240,0,700,2,240
2,72,0,2,1,0,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0
3,67,0,1,5,0,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0
4,72,0,1,1,0,2,2,2,2,2,...,0,30,40,0,220,80,0,250,2,120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116347,65,0,2,1,0,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0
116348,92,0,2,1,0,2,2,2,2,2,...,0,1570,780,0,1370,350,0,2940,3,1130
116349,69,0,2,1,0,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0
116350,97,0,1,1,0,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0
116351,56,0,2,1,0,1,2,1,2,1,...,0,2870,1260,0,3280,910,0,6150,4,2170

In [32]:
x=df.iloc[:,0:16]
y=df['RiskT']
x

,age,Dead,Sex,Race,Esrd,ALZ,CHF,KIDN,CNC,COPD,DEP,DIA,HEART,OSTEO,ARTH,STK
0,85,0,1,1,0,2,2,2,2,2,2,2,2,2,2,2
1,65,0,1,1,0,2,2,2,2,2,2,2,2,2,2,2
2,72,0,2,1,0,2,2,2,2,2,2,2,2,2,2,2
3,67,0,1,5,0,2,2,2,2,2,2,2,2,2,2,2
4,72,0,1,1,0,2,2,2,2,2,2,2,2,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116347,65,0,2,1,0,2,2,2,2,2,2,2,2,2,2,2
116348,92,0,2,1,0,2,2,2,2,2,1,1,1,1,1,2
116349,69,0,2,1,0,2,2,2,2,2,2,2,2,2,2,2
116350,97,0,1,1,0,2,2,2,2,2,2,2,2,2,2,2
116351,56,0,2,1,0,1,2,1,2,1,1,1,1,2,1,2

In [33]:

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=0)

In [43]:
logreg = LogisticRegression(solver='lbfgs', max_iter=5000)

logreg.fit(X_train,y_train)
test_pred=logreg.predict(X_test)

In [45]:
print('Accuracy = {:.5f}'.format(accuracy_score(y_test, test_pred)))

Accuracy = 0.63175

In [46]:
y_pred=logreg.predict(X_train)

In [47]:
print('Accuracy = {:.5f}'.format(accuracy_score(y_train, y_pred)))

Accuracy = 0.62353

In [48]:
print('\nClassification Report')
print(classification_report(y_test, test_pred))

Classification Report
              precision    recall  f1-score   support

           0       0.68      0.99      0.81      3088
           1       0.00      0.00      0.00       235
           2       0.55      0.41      0.47      2842
           3       0.50      0.42      0.46      2630
           4       0.73      0.71      0.72      2841

    accuracy                           0.63     11636
   macro avg       0.49      0.51      0.49     11636
weighted avg       0.60      0.63      0.61     11636

C:\Users\SHREYAN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\SHREYAN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\SHREYAN\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [60]:
df=df.drop(df[df.TotalPre==0].index)
df

,age,Dead,Sex,Race,Esrd,ALZ,CHF,KIDN,CNC,COPD,...,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR,TotalClaims,RiskT,TotalPre
0,85,0,1,1,0,2,2,2,2,2,...,0,50,10,0,0,0,0,50,1,10
1,65,0,1,1,0,2,2,2,2,2,...,0,0,0,0,700,240,0,700,2,240
4,72,0,1,1,0,2,2,2,2,2,...,0,30,40,0,220,80,0,250,2,120
6,86,0,1,1,0,2,1,1,2,2,...,0,1010,270,0,3330,940,0,4340,4,1210
7,73,0,1,1,0,2,2,2,2,2,...,0,150,160,0,870,340,80,1020,2,500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116343,67,0,2,1,0,2,2,2,2,2,...,0,120,30,0,170,40,0,290,2,70
116345,72,0,2,1,0,2,2,2,2,2,...,0,50,30,0,100,30,0,10470,4,1084
116346,69,0,1,1,0,2,2,2,2,2,...,0,0,0,0,640,110,10,640,2,110
116348,92,0,2,1,0,2,2,2,2,2,...,0,1570,780,0,1370,350,0,2940,3,1130
116351,56,0,2,1,0,1,2,1,2,1,...,0,2870,1260,0,3280,910,0,6150,4,2170

In [95]:
y=df['TotalPre']
x=df.iloc[:,0:16]

In [70]:
model = LinearRegression()
model.fit(x, y)

LinearRegression()

In [69]:
import statsmodels.api as sm
results = sm.OLS(y,x).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:               TotalPre   R-squared (uncentered):                   0.494
Model:                            OLS   Adj. R-squared (uncentered):              0.494
Method:                 Least Squares   F-statistic:                              5123.
Date:                Wed, 20 Oct 2021   Prob (F-statistic):                        0.00
Time:                        01:22:39   Log-Likelihood:                     -7.2284e+05
No. Observations:               83934   AIC:                                  1.446e+06
Df Residuals:                   83918   BIC:                                  1.446e+06
Df Model:                          16
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
age           23.7149      0.329     72.067      0.000      23.070      24.360
Dead        -519.4425     43.102    -12.051      0.000    -603.922    -434.963
Sex          226.9023      9.160     24.771      0.000     208.949     244.856
Race         133.9055      6.385     20.971      0.000     121.391     146.420
Esrd        1238.8464     16.711     74.132      0.000    1206.092    1271.601
ALZ         -130.5603     11.211    -11.646      0.000    -152.533    -108.588
CHF         -313.7188     10.862    -28.883      0.000    -335.007    -292.430
KIDN        -491.9019     13.426    -36.638      0.000    -518.217    -465.587
CNC          229.2800     15.232     15.053      0.000     199.426     259.134
COPD        -466.0186     13.017    -35.801      0.000    -491.532    -440.505
DEP         -115.7715     10.718    -10.801      0.000    -136.779     -94.764
DIA         -189.6657     10.554    -17.971      0.000    -210.352    -168.980
HEART       -272.0983     10.554    -25.781      0.000    -292.785    -251.412
OSTEO        179.7307     10.883     16.514      0.000     158.399     201.062
ARTH          32.7597     11.660      2.809      0.005       9.905      55.614
STK          608.0571     17.486     34.774      0.000     573.784     642.330
==============================================================================
Omnibus:                    92067.690   Durbin-Watson:                   1.992
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         24774942.933
Skew:                           5.190   Prob(JB):                         0.00
Kurtosis:                      86.525   Cond. No.                         690.
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""